"""empty message

Revision ID: 4be33d7d336a
Revises: 1fbd7a379247
Create Date: 2025-04-03 19:16:40.140634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4be33d7d336a'
down_revision = '1fbd7a379247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('character', 'people')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('character_id', new_column_name='people_id')
        batch_op.drop_constraint('favorite_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('favorite_people_id_fkey', 'people', ['people_id'], ['id'], ondelete='CASCADE')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('people_id', new_column_name='character_id')
        batch_op.drop_constraint('favorite_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('favorite_character_id_fkey', 'character', ['character_id'], ['id'], ondelete='CASCADE')


    op.rename_table('people', 'character')

    # ### end Alembic commands ###
